### ISSUE TITLE
How do I specify security token?

### ISSUE THREAD

**Issue by ajayinfoworks** [datadudes/salesforce2hadoop#10]
First time I ran this tool, I got this message:

```
Exception in thread "main" [LoginFault [ApiFault  exceptionCode='LOGIN_MUST_USE_SECURITY_TOKEN'
 exceptionMessage='Invalid username, password, security token; or user locked out. Are you at a new location? When accessing Salesforce--either via a desktop client or the API--from outside of your company’s trusted networks, you must add a security token to your password to log in. To get your new security token, log in to Salesforce. From your personal settings, enter Reset My Security Token in the Quick Find box, then select Reset My Security Token.'
```

So I created a new security token but I don't know how to pass it to this tool. Please explain. Thanks.

**Comment by ajayinfoworks** [comment]
Added 'Security Token' to the end of the password as suggested at the following link & got past this issue.

https://docs.servicerocket.com/pages/viewpage.action?pageId=5967258

**Comment by Henry922** [comment]
Hi I've got the same error and i've added my security Token
as below <password><securitytoken>, however i've received another error as below, any ideas?

java -jar sf2hadoop.jar init -u henry922@yahoo.com -p pwdtCA5ShLuXOt0ZTLDO4Ea9NW
-bash: !tCA5ShLuXOt0ZTLDO4Ea9NW: event not found

**Comment by Henry922** [comment]
java -jar sf2hadoop.jar init -u henry922@yahoo.com -p <password>tCA5ShLuXOt0ZTLDO4Ea9NW
-bash: !tCA5ShLuXOt0ZTLDO4Ea9NW: event not found

**Comment by DonDebonair** [comment]
@Henry922 your error is different. Your security token contains a `!` apparently? And your shell (Bash) can't deal with that. Try putting your security token between quotes
