### ISSUE TITLE
Accounts not getting pulled down

### ISSUE THREAD

**Issue by ajayinfoworks** [datadudes/salesforce2hadoop#11]
I created 2 accounts on Salesforce. Both of them are 'active' but when I run the following command I get:

"Processed 0 records"

What am I doing wrong? Please help. Thanks.

---command----
`java -jar ./target/scala-2.11/salesforce2hadoop-assembly-1.2.jar init -u <id> -p <password> -b file:///tmp/salesforce/ -w /Users/xxx/Downloads/sfdc-enterprise.wsdl -s /tmp/state-file/state.out Account`
---- end command ----

Also when I run this command:

`java -jar avro-tools-1.8.1.jar totext /tmp/salesforce/account/2cf9d3bd-400b-43a2-89a4-5ec6dcd2c687.avro a.out`

I get:

```
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Avro file is not generic text schema
No options specified  

```

**Comment by DonDebonair** [comment]
Hi, the "Processed 0 records" message is a bit misleading. It will only print the progress every 2000 records, so when you have less than 2000 records, it will only print the message you saw, even when it actually processed > 0 records.
So I have a feeling that your AVRO file actually contains records. The other problem is avro-tools not showing your data, which I think has to do with not specifying the schema/specifying "text schema"? (which it isn't)

**Comment by ajayinfoworks** [comment]
Thanks for the reply. My bad. You're correct. It was working. I looked at the AVRO file using a command similar to the following & saw the json objects:

java -jar avro-tools-1.8.1.jar tojson <avro file location>
