### ISSUE TITLE
Issue with hadoop version 2.8.5

### ISSUE THREAD

**Issue by AmritaKv** [datadudes/salesforce2hadoop#21]
Hi 
Which version of hadoop is supported with this connector?
Recently upgraded to hadoop 2.8.5 and the connector had issues like method not found.
Was working fine for hadoop 2.7.3.
Any plans to upgrade hadoop version?

**Comment by DonDebonair** [comment]
No plans to upgrade the Hadoop version myself. Problem is: I created this at a company I was working for previously, where they used Salesforce. I work at another company where Salesforce is not used, so I have no way to test it.
You're welcome to change and test it yourself and make a PR.
