### ISSUE TITLE
Need help in passing security token

### ISSUE THREAD

**Issue by ramyabalac** [datadudes/salesforce2hadoop#6]
Hi Guys,
Firstly Thank you for an awesome tool. This is exactly what i was looking for, with out having to go through all the APIs.
I have an issue in implementing this, My org has security token enabled for Salesforce and I cannot seem to figure out from the help how to pass this token.

can you please help?

Regards,
Ramya

**Comment by mkrcah** [comment]
Hi Ramya, thanks for the message. According to [this post](https://success.salesforce.com/answers?id=90630000000glADAAY) you should be able to append the security token to the end of the password. Does that work for you?

**Comment by ramyabalac** [comment]
Hi Marcel,

I tried that with out success. I still have authentication issues. Would I
have to regenerate the enterprise.wsdl after reset of password/token?


Regards,
Ramya

On Wed, May 18, 2016 at 4:14 AM, Marcel Krcah <notifications@github.com>
wrote:

> Hi Ramya, thanks for the message. According to this post
> <https://success.salesforce.com/answers?id=90630000000glADAAY> you should
> be able to append the security token to the end of the password. Does that
> work for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/datadudes/salesforce2hadoop/issues/6#issuecomment-219970175>
>



-- 
Regards,
Ramya Chaturvedulla
