### ISSUE TITLE
Using the connector on Salesforce sandbox

### ISSUE THREAD

**Issue by AmritaKv** [datadudes/salesforce2hadoop#7]
Hi 
I am trying to use the salesforce2hadoop connector in the salesforce sandbox as opposed to production.
Is there any way to specify that it is a sandbox?

The wsdl I am using has SOAP location as sandbox like
<soap:address location="https://test.salesforce.com/services/Soap/u/37.0"/>
But When in the source code file **SalesforceService.scala** (apply method line 52) I see the end point being hard coded as https://login.salesforce.com/services/Soap/u/$apiVersion , so it is always going to hit the production env where I don't have access and Hence when I try to use the init command I get error as,

**Exception in thread "main" [LoginFault [ApiFault  exceptionCode='INVALID_LOGIN'
 exceptionMessage='Invalid username, password, security token; or user locked out.'
]**
]

**Comment by DandyDev** [comment]
Hi @AmritaKv! Thanks for trying the connector. I'm sorry it doesn't work for you. The quickest solution for now would be to change the hardcoded url to your sandbox url and build the project again (`sbt assembly` should do the trick).
In the meanwhile, I will see if I can add a parameter for the base url!

**Comment by DandyDev** [comment]
Update! @AmritaKv I've released a new version that will let you configure the base url of the Salesforce instance you want to talk to. You can [download it here](https://github.com/datadudes/salesforce2hadoop/releases/tag/v1.1).

Usage: `java -jar sf2hadoop.jar -a login.of.sf.sandbox.com`

Let me know if that solves your problem!

**Comment by AmritaKv** [comment]
oh , you are the best !!
thank you for the quick reply...it did solved my problem but got another error same as the other issue that you closed earlier (DatasetNotFoundException - salesforce2hadoop #4)...
