### ISSUE TITLE
Issue with api version other than 32

### ISSUE THREAD

**Issue by AmritaKv** [datadudes/salesforce2hadoop#8]
@DandyDev I am using API version of 37 but there is no way to make it configurable like the base URL.
SalesforceService.scala has it defaulted to 32 which does not work for me.

**Comment by AmritaKv** [comment]
I am trying to build the project locally so I can make the changes but getting some errors with 'sbt assembly'.So though may be quicker for you to fix it.
Thanks for your help!

**Comment by DandyDev** [comment]
I will have a look at it asap. In the meanwhile, can you tell me what kind of build errors you get?

**Comment by DonDebonair** [comment]
I think I fixed the issue. You can now configure the API version from the command line in [this version](https://github.com/datadudes/salesforce2hadoop/releases/tag/v1.2)

**Comment by AmritaKv** [comment]
yes it works now with the version....thanks ...now having issue with Operation timeout..
